Proposal of a CocoaPods support
Liquidsoul/Sourcery-AutoJSONSerializable pull request #2
Opened 2017-05-31 13:27 UTC by MonsieurDart

2017-06-01 20:03 UTC, Liquidsoul commented
Thanks, I'll look into it as soon as I can 😉

2017-06-01 20:45 UTC, Liquidsoul requested changes
Thanks a lot @MonsieurDart ! 🚀 
Just some minor fixes here and there and it will be good to go!
If you don't have the time, I'll try to allocate some to do it in this weekend.

2017-06-01 20:45 UTC, Liquidsoul commented on README.md
> +Add those protocoles anywhere in your source code:
typo here: `protocols`

2017-06-01 20:45 UTC, Liquidsoul commented on LICENSE
> +Copyright (c) 2017 Sébastien Duperron @liquidseb
`@liquidseb` is not relevant here. It should be removed or replaced by my GitHub handle `@liquidsoul`

2017-06-01 20:45 UTC, Liquidsoul commented on README.md
>    * ISO8601 formatted dates
The final dot should be put on every line here or on none. If we put dots, let's not forget this little one here 😉

2017-06-01 20:45 UTC, Liquidsoul commented on README.md
> +protocol AutoJSONSerializable {}
Just a side note here, I'm thinking of removing the need of these protocols altogether and use a Sourcery annotations instead:
```swift
// sourcery: AutoJSONSerializable
struct Contact {
    [...]
}
```

2017-06-01 20:45 UTC, Liquidsoul commented on README.md
> +The current installation process is pretty basic and does not support any dependency managers yet.
Let's remove this sentence, it won't have any sense one this is merged.

2017-06-01 20:45 UTC, Liquidsoul commented on README.md
> +struct Contact, AutoJSONSerializable {
`,` should be `:` for protocol conformance.

2017-06-06 14:48 UTC, MonsieurDart commented on README.md
>    * ISO8601 formatted dates
Done in a following commit.

2017-06-06 14:50 UTC, MonsieurDart commented on README.md
> +Add those protocoles anywhere in your source code:
Yup.

2017-06-06 14:52 UTC, MonsieurDart commented on README.md
> +protocol AutoJSONSerializable {}
Would be cool, indeed! 😊

2017-06-06 14:52 UTC, MonsieurDart commented on README.md
> +struct Contact, AutoJSONSerializable {
My bad… Fixed!

2017-06-06 14:54 UTC, MonsieurDart commented on README.md
> +The current installation process is pretty basic and does not support any dependency managers yet.
Bien vu !

2017-06-06 14:55 UTC, MonsieurDart commented on LICENSE
> +Copyright (c) 2017 Sébastien Duperron @liquidseb
As you wish!

2017-06-08 10:53 UTC, MonsieurDart commented
Let me know if you have other stuff to fix. 😊

2017-06-08 12:11 UTC, Liquidsoul requested changes
Just one remaining typo in the docs I missed before and I'll merge this! 🚀

2017-06-08 12:11 UTC, Liquidsoul commented on README.md
> +If you want to nest some types that are not currently supported (for example: enums with associated values) or if you want to provide a special implementation of the serde methods for those types, yo
Sorry I missed a typo, I suppose you meant `serialize` and not `serde` 😊

2017-06-08 13:24 UTC, MonsieurDart commented
Serde is an (more or less) often used concatenation for "Serialize Deserialize." 😉 



> Le 8 juin 2017 à 14:11, Liquidsoul <notifications@github.com> a écrit :
> 
> @Liquidsoul requested changes on this pull request.
> 
> Just one remaining typo in the docs I missed before and I'll merge this! 🚀
> 
> In README.md <https://github.com/Liquidsoul/Sourcery-AutoJSONSerializable/pull/2#discussion_r120870606>:
> 
> > @@ -114,12 +116,69 @@ struct Contact {
>  }
>  ```
>  
> +## Custom JSON*able Implementation ##
> +
> +If you want to nest some types that are not currently supported (for example: enums with associated values) or if you want to provide a special implementation of the serde methods for those types, you can simply implement the `JSONSerializable` and/or `JSONDeserializable` protocols.
> Sorry I missed a typo, I suppose you meant serialize and not serde 😊
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/Liquidsoul/Sourcery-AutoJSONSerializable/pull/2#pullrequestreview-42870236>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AASCs3z7sXCEsL0G6aIK7c_t3XbRxR6hks5sB-TcgaJpZM4NrobO>.
>

2017-06-08 19:22 UTC, Liquidsoul commented
Didn't know that 😃
Let's merge that then!

2017-06-08 19:22 UTC, Liquidsoul approved these changes

2017-06-08 19:23 UTC, merged